version: "3.7"
services:
  postgres:
    container_name: postgres
    image: postgres:12.2-alpine
    restart: always
    env_file: .env
    ports:
      - 5432:5432
    volumes:
      - ./docker-files/init-dbs.sh:/docker-entrypoint-initdb.d/init-dbs.sh
  keycloak:
    container_name: keycloak
    image: jboss/keycloak:9.0.2
    restart: always
    depends_on:
      - postgres
    env_file: .env
    ports:
      - 8180:8080